water_heater:
  - platform: R4S_G200S
    mac: !secret kettle_mac
    key: 'bbbbbbbbbbbbbbbb'
    scan_interval: 90
    device: hci0

switch:
  - platform: template
    switches:
      kettle:
        value_template: "{{ is_state('water_heater.g200s.operation_mode', 'electric') }}"
        turn_on:
          service: water_heater.set_operation_mode
          data:
            entity_id: water_heater.g200s
            operation_mode: electric
        turn_off:
          service: water_heater.set_operation_mode
          data:
            entity_id: water_heater.g200s
            operation_mode: off

sensor:
  - platform: template
    sensors:
      kettle_sync_time:
        friendly_name: Синхронизировано в
        value_template: "{{ states.water_heater.g200s.attributes.sync_time }}"
      kettle_times:
        friendly_name: Количество включений
        value_template: "{{ states.water_heater.g200s.attributes.times }}"
      kettle_alltime:
        friendly_name: Время работы
        value_template: "{{ states.water_heater.g200s.attributes.alltime }}"
      kettle_energy:
        friendly_name: Потрачено энергии
        value_template: "{{ states.water_heater.g200s.attributes.energy }}"
      kettle_temperature:
        friendly_name: Температура воды в чайнике
        value_template: "{{ states.water_heater.g200s.attributes.current_temperature }}"

automation:
  - alias: Уведомление о кипячении
    hide_entity: True
    trigger:
      - platform: state
        entity_id: water_heater.g200s
        from: "electric"
        to: "off"

    condition:
      - condition: numeric_state
        entity_id: 'sensor.kettle_temperature'
        above: 90

    action:
      - service: notify.telegram_chat_id_1
        data:
          title: '*Чайник вскипячен*'
          message: "{{ state_attr('water_heater.g200s', 'current_temperature') }}"
