vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.7
    token: !secret vacuum_token

input_select:
  vacuum_room:
    name: Комната для уборки
    options:
      - '-'
      - Вся квартира
      - Зал
      - Спальня
      - Кухня
      - Коридор

script:
  vacuum_all:
    alias: "Пропылесосить всю квартиру"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner

  vacuum_living_room:
    alias: "Пропылесосить зал"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone: [[18890,24240,25600,28650]]
          repeats: 2

  vacuum_bedroom:
    alias: "Пропылесосить спальню"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[23812,20690,27330,24500,2]]

  vacuum_kitchen:
    alias: "Пропылесосить кухню"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone: [[21630,28790,25600,33880]]
          repeats: 2

  vacuum_hallway:
    alias: "Пропылесосить коридор"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone: [[25730,24450,30250,31550]]
          repeats: 2

automation:
  - alias: Пылесосить
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room

    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "Вся квартира") %}
            script.vacuum_all
          {% elif is_state("input_select.vacuum_room", "Зал") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Спальня") %}
            script.vacuum_bedroom
          {% elif is_state("input_select.vacuum_room", "Кухня") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Коридор") %}
            script.vacuum_hallway
          {% else %}
          {% endif %}
