input_select:
  vacuum_room:
    name: Комната для уборки
    options:
      - '-'
      - Вся квартира
      - Зал
      - Спальня
      - Кухня
      - Коридор
      - Стандартная уборка

script:
  vacuum_all_default:
    alias: "Стандартная уборка"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: start

  vacuum_living_room:
    alias: "Пропылесосить зал"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: zoned_cleanup
          params:
            zone_ids: ['Living room']

  vacuum_bedroom:
    alias: "Пропылесосить спальню"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: 'zoned_cleanup'
          params:
            zone_ids: ['Bedroom']

  vacuum_kitchen:
    alias: "Пропылесосить кухню"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: zoned_cleanup
          params:
            zone_ids: ['Kitchen']

  vacuum_hallway:
    alias: "Пропылесосить коридор"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: zoned_cleanup
          params:
            zone_ids: ['Hallway']

  vacuum_hall:
    alias: "Пропылесосить прихожую"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: zoned_cleanup
          params:
            zone_ids: ['Hall']

  vacuum_all:
    alias: "Пропылесосить всю квартиру (зонами)"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: zoned_cleanup
          params:
            zone_ids: ['Living room', 'Bedroom', 'Hallway', 'Kitchen', 'Hall']

  vacuum_stop:
    alias: "Остановить уборку"
    sequence:
      - service: vacuum.stop
        data:
          entity_id: vacuum.rockrobo

  vacuum_return_to_base:
    alias: "Возврат на базу"
    sequence:
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.rockrobo

automation:
  - alias: Пылесосить
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room

    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "Вся квартира") %}
            script.vacuum_all
          {% elif is_state("input_select.vacuum_room", "Стандартная уборка") %}
            script.vacuum_all_default
          {% elif is_state("input_select.vacuum_room", "Зал") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Спальня") %}
            script.vacuum_bedroom
          {% elif is_state("input_select.vacuum_room", "Кухня") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Коридор") %}
            script.vacuum_hallway
          {% else %}
          {% endif %}

  - alias: Отправка статуса об уборке
    hide_entity: True
    trigger:
      - platform: state
        entity_id: vacuum.rockrobo
        from: "cleaning"
        to: "idle"
      - platform: state
        entity_id: vacuum.rockrobo
        from: "cleaning"
        to: "docked"
      - platform: state
        entity_id: vacuum.rockrobo
        from: "cleaning"
        to: "returning"

    action:
      - service: notify.telegram_chat_id_1
        data:
          title: '*Уборка окончена*'
          message: "{{ state_attr('vacuum.rockrobo', 'last_run_stats') }}"
          data:
            photo:
              - url: "http://localhost:8123{{ state_attr('camera.rockrobo_map', 'entity_picture') }}"
