vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.7
    token: !secret vacuum_token

input_select:
  vacuum_room:
    name: Комната для уборки
    options:
      - '-'
      - Вся квартира
      - Зал
      - Спальня
      - Кухня
      - Коридор
      - Стандартная уборка

script:
  vacuum_all_default:
    alias: "Стандартная уборка"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner

  vacuum_living_room:
    alias: "Пропылесосить зал"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          coordinates: &living_room_coordinates
          - 18890
          - 24240
          - 25600
          - 28650
          zone:
          - *living_room_coordinates
          repeats: 2

  vacuum_bedroom:
    alias: "Пропылесосить спальню"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          coordinates: &bedroom_coordinates
          - 23812
          - 20690
          - 27330
          - 24500
          - 2
          params:
          - *bedroom_coordinates

  vacuum_kitchen:
    alias: "Пропылесосить кухню"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          coordinates: &kitchen_coordinates
          - 21630
          - 28790
          - 25600
          - 33880
          zone:
          - *kitchen_coordinates
          repeats: 2

  vacuum_hallway:
    alias: "Пропылесосить коридор"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          coordinates: &hallway_coordinates
          - 25730
          - 24450
          - 27330
          - 28950
          zone:
          - *hallway_coordinates
          repeats: 2

  vacuum_hall:
    alias: "Пропылесосить прихожую"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          coordinates: &hall_coordinates
          - 25730
          - 28950
          - 30250
          - 31550
          zone:
          - *hall_coordinates
          repeats: 2

  vacuum_all:
    alias: "Пропылесосить всю квартиру (зонами)"
    sequence:
      - service: vacuum.xiaomi_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
          - *living_room_coordinates
          - *bedroom_coordinates
          - *hallway_coordinates
          - *kitchen_coordinates
          - *hall_coordinates
          repeats: 2

automation:
  - alias: Пылесосить
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room

    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "Вся квартира") %}
            script.vacuum_all
          {% elif is_state("input_select.vacuum_room", "Стандартная уборка") %}
            script.vacuum_all_default
          {% elif is_state("input_select.vacuum_room", "Зал") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Спальня") %}
            script.vacuum_bedroom
          {% elif is_state("input_select.vacuum_room", "Кухня") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Коридор") %}
            script.vacuum_hallway
          {% else %}
          {% endif %}
